### PR TITLE
Make the tooltip markdowns use more vertical space instead of horizontal

### LINKED ISSUE #29: Tooltip formatting after introduction of PrimeReact
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 Enterprise
- VS Code Version: 1.93.1
- Extension Version: Local build of `main` at https://github.com/eclipse-cdt-cloud/vscode-peripheral-inspector/commit/61550b2e2a83c8a59bd6183ee317ca4922cb2758
- Target Device:
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

**To Reproduce**
1. Go to register level (not bit field level).
2. Move the mouse over the register to show the tooltip.

The tooltip seems to be limited to a fixed range.
Longer text items like the 32-bit binary value, but also the `Decimal` heading see line breaks.

**Expected behavior**

Before the change, the tooltip box was wide enough to accommodate the above without line breaks. Width presumably dynamically calculated?

**Code sample and logs**
N/A, use any example

**Screenshots**

Before PrimeReact introduction
image

After PrimeReact introduction
image

**Additional context**

### PR DESCRIPTION
**Pull request by haydar-metin**
Closes #29 

- Use vertical space instead of horizontal
- Fix word breaking

image
image

### CODE REVIEW

File: src/components/tree/integration/peripheral-tree-converter.ts [hunk 1]
```diff
@@ -270,16 +267,20 @@ export class PeripheralRegisterNodeConverter implements TreeResourceConverter<Pe
         const decimal = this.formatValue(resource, resource.currentValue, NumberFormat.Decimal);
         const binary = this.formatValue(resource, resource.currentValue, NumberFormat.Binary);
 
-        mds += ('| Hex &nbsp;&nbsp; | Decimal &nbsp;&nbsp; | Binary &nbsp;&nbsp; |\n');
-        mds += ('|:---|:---|:---|\n');
-        mds += (`| ${hex} &nbsp;&nbsp; | ${decimal} &nbsp;&nbsp; | ${binary} &nbsp;&nbsp; |\n\n`);
+        mds += '**Formats**\n\n';
```
Comment (jreineckearm) [inline src/components/tree/integration/peripheral-tree-converter.ts:270]: Feels a bit like this is redundant and steals valuable space.

File: src/components/tree/integration/peripheral-tree-converter.ts [hunk 2]
```diff
@@ -270,16 +267,20 @@ export class PeripheralRegisterNodeConverter implements TreeResourceConverter<Pe
...
+        mds += `| Binary | ${binary} |\n`;
+        mds += ('\n_____\n\n');
 
         const children = resource.children;
         if (children.length === 0) { return mds; }
 
-        mds += ('**Fields**\n\n');
-        mds += ('| Field | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Bit-Range | Value |\n');
-        mds += ('|:---|:---:|:---|:---|\n');
+        mds += '**Fields**\n\n';
```
Comment (jreineckearm) [inline src/components/tree/integration/peripheral-tree-converter.ts:281]: Again. wondering if we need the `Fields` title if we show headers as the next thing.

**Review by jreineckearm — COMMENTED** [review]
Thanks! Looks IMO better.
Apparently the tooltips require now more vertical space. Where it might be worth in future to investigate if to make the tooltip appear above the mouse-pointer to fit in more content (e.g. if many bit fields for a register). See two suggestions which could already help a little.

**Comment by haydar-metin** [comment]
@jreineckearm done!

**Review by jreineckearm — APPROVED** [review]
Awesome, thanks!
