### PR TITLE
Correctly handle debug-tracker-vscode terminated event

### LINKED ISSUE #63: Peripheral Inspector does not clear on disconnect if using debug-tracker-vscode
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 11 Enterprise
- VS Code Version: 1.99.2
- Extension Version: 1.7.0
- Target Device: Any
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

If I disconnect from a debug session that populates the Peripheral Inspector, the view does not clear if the `mcu-debug.vscode-debug-tracker` extension is active, too.

**To Reproduce**
1. Install and activate the debug tracker extension
2. Start debug session and wait until Peripheral Inspector is populated.
3. Disconnect session. 
4. The view does not clear/remove data for the closed session

**Expected behavior**

Expectation is that the Peripheral Inspector contents clears for the just closed session.

**Additional context**

The debug tracker extension support in the Peripheral Inspector expects the received `terminated` event to contain full session information. But the debug tracker extension only sends the session ID.

### PR DESCRIPTION
**Pull request by jreineckearm**
Closes #63 

Root cause is that the debug-tracker-vscode extension only sends a session ID but not the full session information as the original events do. The Peripheral Inspector doesn't handle that correctly while it should support events tracked by this extension. It is used by a couple of debug adapters out there.

This PR changes the terminated event handling to deal with just the session ID coming in.

### CODE REVIEW

File: src/debug-tracker.ts [hunk 1]
```diff
@@ -65,8 +66,8 @@ export class DebugTracker {
                         if (event.event === DebugSessionStatus.Initializing && event.session) {
                             this.handleOnWillStartSession(event.session);
                         }
-                        if (event.event === DebugSessionStatus.Terminated && event.session) {
```
Comment (thorstendb-ARM) [inline src/debug-tracker.ts:68]: Looks good in general, but would keep the old code (as if defined) as a fallback if dependency is fixed some time.

Comment (jreineckearm) [reply src/debug-tracker.ts:68]: Good thinking, will change that part to be more robust.

Comment (jreineckearm) [reply src/debug-tracker.ts:68]: Done

**Comment by jreineckearm** [comment]
@thorstendb-ARM , could you please have another look at the changes and approve if you are happy with them?

**Review by thorstendb-ARM — APPROVED** [review]
looks great
